Fix various things with the script and user being used

diff --git a/roles/commcare_analytics/templates/create_postgres_dump.sh.j2 b/roles/commcare_analytics/templates/create_postgres_dump.sh.j2
--- a/roles/commcare_analytics/templates/create_postgres_dump.sh.j2
+++ b/roles/commcare_analytics/templates/create_postgres_dump.sh.j2
@@ -22,7 +22,7 @@ do
     destination="$BACKUP_DIRECTORY/$db_name.dump"
     log "Dumping $db_name to $destination";
 
-    pg_dump -w --dbname=$db_name --user="{{ postgresql_user }}" --port="{{ default_db_port }}" --host="{{ default_db_host }}" --file=$destination;
+    pg_dump -w --dbname=$db_name --user="{{ default_db_user }}" --port="{{ default_db_port }}" --host="{{ default_db_host }}" --file=$destination;
 
     if [[ $? -ne 0 ]] ; then
         log "Unable to dump database '$db_name'";
@@ -32,13 +32,25 @@ done
 
 #Create archive
 log "Compressing and archiving database dumps";
-tar --zstd -cf $BACKUP_DIRECTORY.tar.zst $BACKUP_DIRECTORY;
+tar --gzip -cf $BACKUP_DIRECTORY.tar.zst $BACKUP_DIRECTORY;
+if [[ $? -ne 0 ]] ; then
+    log "Something went wrong while archiving.";
+    exit 1
+fi
 
 #Upload to S3
 log "Uploading to S3";
-/usr/local/bin/aws s3api put-object --bucket "{{ vault_s3_bucket }}" --key $BACKUP_NAME --server-side-encryption AES256 --body $BACKUP_DIRECTORY.tar.zst
+aws s3api put-object --bucket "{{ vault_s3_bucket }}" --key $BACKUP_NAME --server-side-encryption AES256 --body $BACKUP_DIRECTORY.tar.zst
+if [[ $? -ne 0 ]] ; then
+    log "Upload was not successful.";
+    exit 1
+fi
 
 log "Cleaning up local dumps";
 rm -rf $BACKUP_DIRECTORY $BACKUP_DIRECTORY.tar.zst;
+if [[ $? -ne 0 ]] ; then
+    log "Failed to remove files from local machine";
+    exit 1
+fi
 
 exit 0
